# Generated by Django 3.1.5 on 2021-01-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imagwe',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
