# Generated by Django 3.1.5 on 2021-01-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='imagwe2',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
